export const CREATE_DRIVER_REQUEST = "CREATE_DRIVER_REQUEST";
export const CREATE_DRIVER_SUCCESS = "CREATE_DRIVER_SUCCESS";
export const CREATE_DRIVER_FAIL = "CREATE_DRIVER_FAIL";

export const DRIVER_APPROVED_REQUEST = "DRIVER_APPROVED_REQUEST";
export const DRIVER_APPROVED_SUCCESS = "DRIVER_APPROVED_SUCCESS";
export const DRIVER_APPROVED_FAIL = "DRIVER_APPROVED_FAIL";

export const DRIVER_REJECTED_REQUEST = "DRIVER_REJECTED_REQUEST";
export const DRIVER_REJECTED_SUCCESS = "DRIVER_REJECTED_SUCCESS";
export const DRIVER_REJECTED_FAIL = "DRIVER_REJECTED_FAIL";

export const DRIVER_LIST_REQUEST = "DRIVER_LIST_REQUEST";
export const DRIVER_LIST_SUCCESS = "DRIVER_LIST_SUCCESS";
export const DRIVER_LIST_FAIL = "DRIVER_LIST_FAIL";

export const DRIVER_LIST_DISAPPROVED_REQUEST = "DRIVER_LIST_DISAPPROVED_REQUEST";
export const DRIVER_LIST_DISAPPROVED_SUCCESS = "DRIVER_LIST_DISAPPROVED_SUCCESS";
export const DRIVER_LIST_DISAPPROVED_FAIL = "DRIVER_LIST_DISAPPROVED_FAIL";

export const SINGLE_DRIVER_REQUEST = "SINGLE_DRIVER_REQUEST";
export const SINGLE_DRIVER_SUCCESS = "SINGLE_DRIVER_SUCCESS";
export const SINGLE_DRIVER_FAIL = "SINGLE_DRIVER_FAIL";

export const DELETE_DRIVER_REQUEST = "DELETE_DRIVER_REQUEST";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DELETE_DRIVER_FAIL = "DELETE_DRIVER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";