export const PWD_LIST_REQUEST = 'PWD_LIST_REQUEST'
export const PWD_LIST_SUCCESS = 'PWD_LIST_SUCCESS'
export const PWD_LIST_FAIL = 'PWD_LIST_FAIL'

export const PWD_REGISTER_REQUEST = 'PWD_REGISTER_REQUEST'
export const PWD_REGISTER_SUCCESS = 'PWD_REGISTER_SUCCESS'
export const PWD_REGISTER_FAIL = 'PWD_REGISTER_FAIL'

export const PWD_SINGLE_REQUEST = 'PWD_SINGLE_REQUEST'
export const PWD_SINGLE_SUCCESS = 'PWD_SINGLE_SUCCESS'
export const PWD_SINGLE_FAIL = 'PWD_SINGLE_FAIL'

export const PWD_APPROVE_LIST_REQUEST = 'PWD_APPROVE_LIST_REQUEST'
export const PWD_APPROVE_LIST_SUCCESS = 'PWD_APPROVE_LIST_SUCCESS'
export const PWD_APPROVE_LIST_FAIL = 'PWD_APPROVE_LIST_FAIL'

export const PWD_APPROVE_REQUEST = 'PWD_APPROVE_REQUEST'
export const PWD_APPROVE_SUCCESS = 'PWD_APPROVE_SUCCESS'
export const PWD_APPROVE_FAIL = 'PWD_APPROVE_FAIL'

export const PWD_REJECT_REQUEST = 'PWD_REJECT_REQUEST'
export const PWD_REJECT_SUCCESS = 'PWD_REJECT_SUCCESS'
export const PWD_REJECT_FAIL = 'PWD_REJECT_FAIL'