export const SENIOR_LIST_REQUEST = 'SENIOR_LIST_REQUEST'
export const SENIOR_LIST_SUCCESS = 'SENIOR_LIST_SUCCESS'
export const SENIOR_LIST_FAIL = 'SENIOR_LIST_FAIL'

export const SENIOR_REGISTER_REQUEST = 'SENIOR_REGISTER_REQUEST'
export const SENIOR_REGISTER_SUCCESS = 'SENIOR_REGISTER_SUCCESS'
export const SENIOR_REGISTER_FAIL = 'SENIOR_REGISTER_FAIL'

export const SENIOR_SINGLE_REQUEST = 'SENIOR_SINGLE_REQUEST'
export const SENIOR_SINGLE_SUCCESS = 'SENIOR_SINGLE_SUCCESS'
export const SENIOR_SINGLE_FAIL = 'SENIOR_SINGLE_FAIL'

export const SENIOR_APPROVE_LIST_REQUEST = 'SENIOR_APPROVE_LIST_REQUEST'
export const SENIOR_APPROVE_LIST_SUCCESS = 'SENIOR_APPROVE_LIST_SUCCESS'
export const SENIOR_APPROVE_LIST_FAIL = 'SENIOR_APPROVE_LIST_FAIL'

export const SENIOR_APPROVE_REQUEST = 'SENIOR_APPROVE_REQUEST'
export const SENIOR_APPROVE_SUCCESS = 'SENIOR_APPROVE_SUCCESS'
export const SENIOR_APPROVE_FAIL = 'SENIOR_APPROVE_FAIL'

export const SENIOR_REJECT_REQUEST = 'SENIOR_REJECT_REQUEST'
export const SENIOR_REJECT_SUCCESS = 'SENIOR_REJECT_SUCCESS'
export const SENIOR_REJECT_FAIL = 'SENIOR_REJECT_FAIL'
