export const WEATHER_DAILY_REQUEST = "WEATHER_DAILY_REQUEST";
export const WEATHER_DAILY_SUCCESS = "WEATHER_DAILY_SUCCESS";
export const WEATHER_DAILY_FAIL = "WEATHER_DAILY_FAIL";

export const WEATHER_CURRENT_REQUEST = "WEATHER_CURRENT_REQUEST";
export const WEATHER_CURRENT_SUCCESS = "WEATHER_CURRENT_SUCCESS";
export const WEATHER_CURRENT_FAIL = "WEATHER_CURRENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";