import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  overallContainer: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  mapContainer: {
    height: height * 0.60,
    marginTop: height * 0.015,
    borderRadius: width * 0.03,
    overflow: "hidden",
    borderColor: "#ccc",
    borderWidth: width * 0.003,
    marginHorizontal: width * 0.03,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  cardContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: width * 0.035,
    marginHorizontal: width * 0.03,
    marginBottom: height * 0.01,
    backgroundColor: "white",
    borderRadius: width * 0.025,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginTop: height * 0.03,
    borderWidth: width * 0.003,
    borderColor: "#e1e1e1",
  },
  imageContainer: {
    width: width * 0.12,
    height: width * 0.12,
    marginRight: width * 0.035,
    borderRadius: width * 0.02,
    overflow: "hidden",
    borderWidth: width * 0.003,
    borderColor: "#ccc",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  detailsContainer: {
    flex: 1,
  },
  farmName: {
    fontSize: width * 0.045,
    fontWeight: "600",
    marginBottom: height * 0.003,
    color: "#002b5e",
  },
  address: {
    fontSize: width * 0.035,
    color: "#444",
    marginBottom: height * 0.006,
  },
  viewButton: {
    backgroundColor: "#00489a",
    paddingVertical: height * 0.012,
    paddingHorizontal: width * 0.04,
    borderRadius: width * 0.02,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 3,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: width * 0.032,
    fontWeight: "500",
    textAlign: "center",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  detailContainerNull: {
    backgroundColor: "white",
    padding: width * 0.03,
    margin: width * 0.025,
    borderRadius: width * 0.02,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1.5,
    alignItems: "center",
  },
  textNullDetail: {
    textAlign: "center",
    fontSize: width * 0.037,
    color: "#444",
    fontWeight: "500",
  },
});