module.exports = {
    USER: "user",
    PRODUCT: "product",
    CONVERSATION: "conversation",
    MESSAGES: "messages",
    UNSENT_MESSAGES: "unsentmessages",
    ADDRESS: "address",
    SHIPPING: "shipping",
    ORDER: "order",
    JWT: "jwt",
    NONE: "none",
    IMAGES: "images",
    IMAGE: "image",
    FARMINFO: "farminfo",
    COMMENT: "comment",
    POST: "post",
    SHAREPOST: "sharepost",
}