import { MAP_API_1, BASE_ADDRESS, BASE_ADDRESS_1, SOCKET_ADDRESS, ALT_BASE_ADDRESS } from "@env";



export default {
  MAP_API_1: MAP_API_1 || process.env.MAP_API_1,
  BASE_ADDRESS: BASE_ADDRESS || process.env.BASE_ADDRESS,
  BASE_ADDRESS_1: BASE_ADDRESS_1 || process.env.BASE_ADDRESS_1,
  SOCKET_ADDRESS: SOCKET_ADDRESS || process.env.SOCKET_ADDRESS,
  ALT_BASE_ADDRESS: ALT_BASE_ADDRESS || process.env.ALT_BASE_ADDRESS,
};
