const filLanguage = {
    labels: {
        'bobo': -3,
        'tanga': -2,
        'mabait': 2,
        'mahusay': 3,
        'maganda': 3,
        'panget': -3,
        'masama': -3,
        'masarap': 3,
        'masakit': -3,
        'masaya': 3,
        'malungkot': -3,
        'malas': -3,
        'malakas': 3,
        'mahina': -3,
        'mabaho': -3,
        'mabuti': 3,
        'mahirap': -3,
        'madali': 3,
        'maliit': -3,
        'malaki': 3,
        'malinis': 3,
        'mabigat': -3,
        'magaan': 3,
        'mabagal': -3,
        'mabilis': 3,
        'mabango': 3,
        'inip' : -2,
        'gutom': -3,
        'sakit': -3,
        'saya': 3,
        'iyak': -3,
        'tawa': 3,
        'takot': -3,
        'galit': -3,
        'pagod': -3,
        'gusto': 3,
        'ayaw': -3,
        'nababalisa': -3,
        'nagagalit': -3,
        'nagugutom': -3,
        'salungat': -2,
        'inisin' : -2,
        'balisa' : -3,
        'kawalang interes' : -3,
        'mayabang' : -3,
        'walang kwenta' : -3,
        'may tinik' : -3,
        'mabangis' : -3,
        'bulok' : -2,
        'sira' : -3,
        'pabaya': -3,
        'baliw': -3,
        'nabubulok': -3,
        'nababaliw': -3,
        'nakakaasar': -3,
        'nakakainis': -3,
        'marumi': -2,
        'nakakaumay': -2,
        'nakakasuka': -3,
        'nakakatakot': -3,
        'nakakalungkot': -3,
        'nakakasusuklam' : -3,
        'napakarumi': -2,
        'may sira': -3,
        'hindi tinangap': -3,
        'hindi' : -1,
        'hindi maganda' : -2,
        'hindi masarap' : -2,
        'hindi mabuti' : -2,
        'mahirap' : -1,
        'mahirap kainin' : -2,
        'mahirap ayusin' : -2,
        'mahirap gamitin' : -2,
        'mahirap intindihin' : -2,
        'mahirap hanapin' : -2,
        'mahirap gawin' : -2,
        'mahirap sundan' : -2,
        'mahirap basahin' : -2,
        'mahirap isipin' : -2,
        'mahirap tandaan' : -2,
        'mahirap pakisamahan' : -2,
        'mahirap patawarin' : -2,
        'mahirap pigilan' : -2,
        'kontrabida' : -2,
        'kontra' : -1,
        'kontra sa' : -2,
        'kontra sa akin' : -2,
        'kontra sa lahat' : -2,
        'kontra sa gusto' : -2,
        'kontra sa akin' : -2,
        'kontra sa lahat' : -2,
        'walang kwenta' : -2,
        'walang kwenta sa akin' : -2,
        'walang kwenta sa lahat' : -2,
        'walang kwenta sa gusto' : -2,
        'walang kwenta sa akin' : -2,
        'po' : 1,
        'opo' : 1,
        'ho' : 1,
        'salamat' : 3,
        'salamat po' : 3,
        'salamat ho' : 3,
        'mahal' : 3,
        'panis' : -2,
        'panis na' : -3,
        'magaan' : 1,
        'mura' : 1,
        'napakamura' : 3,
        'napakamahal' : -3,
        'maarte' : -2,
        'bastos' : -3,
        'luma' : -2,
    }
};

module.exports = { filLanguage };
